- name: Configure WanderWise Web Server
  hosts: webservers
  become: yes

  tasks:
    - name: Install Docker
      amazon-linux-extras:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /home/ec2-user/docker-compose.yml

    - name: Copy .env file
      copy:
        src: .env
        dest: /home/ec2-user/.env

    - name: Pull and run application
      docker_compose:
        project_src: /home/ec2-user
        state: present

    - name: Check Docker service status
      service_facts:
      register: docker_status