---
- name: Configure WanderWise Web Server
  hosts: webservers
  become: yes
  gather_facts: yes
  vars:
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    # - name: Install Docker
    #   yum:
    #     name: docker
    #     state: present
    #   become: yes
    - name: Install Docker Python library
      pip:
        name: docker-py
        state: present
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
      become: yes

    - name: Create docker-compose.yml
      copy:
        content: |
          version: '3'
          services:
            web:
              image: isuruamarasena/wanderwise:latest
              ports:
                - "3000:3000"
              environment:
                - DB_USER=${DB_USER}
                - DB_PASSWORD=${DB_PASSWORD}
                - DB_NAME=${DB_NAME}
                - DB_HOST=${DB_HOST}
                - JWT_SECRET=${JWT_SECRET}
                - NODE_ENV=production
        dest: /home/ec2-user/docker-compose.yml

    - name: Copy .env file
      copy:
        src: .env
        dest: /home/ec2-user/.env

    - name: Pull and run Docker container
      docker_container:
        name: wanderwise
        image: isuruamarasena/wanderwise:latest
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
        env_file: /home/ec2-user/.env